# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# relative_permalinks: true
gems: [jekyll-paginate]
# Setup
title:               介绍
tagline:             'A text theme'
description:         'my name is 于利柱. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 http://lanyon.getpoole.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Yulz
  url:               ‘’
  email:             191237647@qq.com

# Custom vars
version:             1.0.0
